repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    - id: flake8
      additional_dependencies: [flake8-docstrings]
    - id: check-added-large-files
      args: ['--maxkb=1500']
    - id: detect-private-key
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: ''
    hooks:
    -   id: eslint
        additional_dependencies:
        -   eslint@7.29.0
        -   eslint-config-airbnb@18.2.1
        -   eslint-plugin-import@2.23.4
        -   eslint-plugin-jsx-a11y@6.4.1
        -   eslint-plugin-react@7.24.0
        -   eslint-plugin-react-hooks@4.2.0
