repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # pre-commit-hooks version
    hooks:
      - id: check-added-large-files
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --config=server/pyproject.toml]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.20.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint@7.29.0
          - eslint-config-airbnb@18.2.1
          - eslint-plugin-import@2.23.4
          - eslint-plugin-jsx-a11y@6.4.1
          - eslint-plugin-react@7.24.0
          - eslint-plugin-react-hooks@4.2.0
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
minimum_pre_commit_version: 3.7.1
